[package]
name = "jack"
version = "0.1.0"
authors = ["IGI-111 <igi-111@protonmail.com>"]
edition = "2018"

[lib]
name = "jack_lang"
path = "src/lib.rs"

[[bin]]
name = "jack"
path = "src/bin.rs"

[dependencies]
nom = "6.1.2"
err-derive = "0.3.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
llvm-ir = { version = "0.9.0", features = ["llvm-14"] }
